### ISSUE TITLE
Does not save finished image into folder

### ISSUE THREAD

**Issue by Skumball** [pkuliyi2015/sd-webui-stablesr#48]
With WebUI 1.6.0 update the StableSR script no longer saves the image into the chosen paths directory. Not sure where it goes but I have to right-click and copy it or download it for now.

**Comment by Skumball** [comment]
Using SpaceSniffer while generating the image it goes into AppData\Local\Temp\Gradio

**Comment by 773774775** [comment]
It should be a program bug. I also used GIT PULL to upgrade from version 1.5.2 to version 1.6. This problem occurred, and it was solved after a new installation with git clone.

**Comment by Zuco-M** [comment]
Have you solved this problem? I meet it, too

**Comment by Skumball** [comment]
No, still not been fixed. I use Double Commander as a file manager and have the Gradio folder bookmarked so I can quickly find it until this has been fixed.

**Comment by Skumball** [comment]
Just found out that changing Color Fix to None puts the image in the right place.

**Comment by DrUmranAli** [comment]
I've found the image output folder (using 1.6 too) but not the saved metadata (.txt file) anyone figure out where it is saving it(it's not in the temp/gradio folder...)
